### PR TITLE
Replace ReflectionParameter::getClass by ::getType

### PR DESCRIPTION
**Pull request by jaapio**
php8 deprecates the usage of ::getClass. So switch to an implementation using getType equal to the existing resolveUnionTypes function.

### CODE REVIEW

**Comment by jaapio** [comment]
Thanks @mikey179

**Comment by mikey179** [comment]
Unfortunately I‘m currently in a hospital (luckily not Covid-related) and don‘t have the tools available to create a proper release, a situation that won‘t change in the next 5 or 6 weeks. I just tried something on iPad, but it didn‘t work out as I hoped. If you like to I can provide you with the permissions necessary to create a proper one. The following things should be done for a release:

- [ ] Tag release (preferably with a signed tag, but that‘s up to you)
- [ ] Push release tag

**Comment by jaapio** [comment]
Hope you will have a nice Christmas in the hospital and everything will be better next year. 

If you can provide me the required permissions I'm happy to help you to move this project forward.

**Comment by mikey179** [comment]
Thank you @jaapio.

I just created a team and added you and the repo to it, so you should be able to push, pull and tag. Let me know if something doesn’t work.

**Comment by jaapio** [comment]
Hi @mikey179 

I don't have the correct permissions yet to push the newly created tag. Could you please have a look?

**Comment by mikey179** [comment]
I forgot to set the correct permission level for the repo in the team, adding the repo puts it into read mode only. Switched to write.

**Pull request merged**
